'use strict';
// ══════════════════════════════════════════════════════════════════
// convenioData.js — PilotPay Convenio Engine
// Base normativa del motor de nómina. Solo lectura.
// No interactúa con Firebase ni con el DOM.
// Actualizar únicamente con evidencia verificada.
// ══════════════════════════════════════════════════════════════════

// ── Enumeraciones ──────────────────────────────────────────────────

const CVN_ESTADO = {
  IMPLEMENTADO:         'implementado',
  IMPLEMENTADO_PARCIAL: 'implementado_parcial',
  DOCUMENTADO:          'documentado',
  PENDIENTE_EVIDENCIA:  'pendiente_evidencia',
  PENDIENTE_CALCULO:    'pendiente_calculo',
  PENDIENTE_VALIDACION: 'pendiente_validacion',
};

const CVN_PRIORIDAD = {
  CRITICA: 'critica',
  ALTA:    'alta',
  MEDIA:   'media',
  BAJA:    'baja',
};

const CVN_CONFIANZA = {
  VALIDADO_NOMINA:   'validado_nomina',   // verificado contra nómina real
  VALIDADO_CONVENIO: 'validado_convenio', // verificado contra texto del CC
  PARCIAL:           'parcial',           // interpretación parcial, pendiente contraste
  EXPERIMENTAL:      'experimental',      // sin evidencia documental suficiente
};

const CVN_IMPACTO = {
  NOMINA:         'nomina',         // afecta directamente al cálculo de nómina
  OPERATIVO:      'operativo',      // afecta a la operación laboral, no a la nómina
  DOCUMENTAL:     'documental',     // relevancia informativa / documental
  ADMINISTRATIVO: 'administrativo', // afecta a procedimientos / gestión
};

// ── Categorías ────────────────────────────────────────────────────

const CONVENIO_CATEGORIAS = [
  { id: 'fijos',            label: 'Conceptos fijos',      icon: '💰', orden: 1 },
  { id: 'variables',        label: 'Variables',            icon: '📊', orden: 2 },
  { id: 'dietas',           label: 'Dietas',               icon: '🍽', orden: 3 },
  { id: 'complementos',     label: 'Complementos',         icon: '⚙️',  orden: 4 },
  { id: 'cargos_especiales',label: 'Cargos especiales',    icon: '🎖',  orden: 5 },
  { id: 'it_bajas',         label: 'IT / Bajas',           icon: '🏥', orden: 6 },
  { id: 'permisos',         label: 'Permisos / Licencias', icon: '📅', orden: 7 },
  { id: 'acumuladas',       label: 'Variables acumuladas', icon: '📈', orden: 8 },
  { id: 'uniformidad',      label: 'Uniformidad',          icon: '👔', orden: 9 },
];

// ── Catálogo de conceptos ─────────────────────────────────────────
//
// Convenciones:
//   null en campos fiscales/SS = pendiente de evidencia
//   motor_key = null si no está implementado en payrollEngine
//   notas_pendientes = qué hace falta para avanzar de estado

const CONVENIO_CONCEPTOS = [

  // ─────────────────────────────────────────────────────────────
  // CONCEPTOS FIJOS
  // ─────────────────────────────────────────────────────────────

  {
    id:               'salario_base',
    nombre:           'Salario Base',
    nombre_corto:     'SB',
    categoria:        'fijos',
    tags:             ['mensual', 'tablas', 'nivel', 'fijo'],
    articulo:         'Anexo I · BCSA 2026',
    boe:              'BOE-A-2026-XXXX',
    vigencia_desde:   '2026-01-01',
    vigencia_hasta:   null,
    definicion:       'Retribución mensual fija establecida por cargo (CMD/COP/TCP) y nivel de antigüedad. Base sobre la que se construye el resto de la nómina.',
    condiciones:      [
      'Depende del cargo: Comandante, Copiloto, TCP/SCC/CC',
      'Varía por nivel (1–6 en pilotos, 1–5 en TCP)',
      'No varía por base ni por actividad mensual',
    ],
    aplica_a:         ['CMD', 'COP', 'TCP', 'SCC', 'CC'],
    por_nivel:        true,
    por_base:         false,
    cotiza_ss:        true,
    tributa_irpf:     true,
    exento_hasta:     null,
    afecta_base_ss:   true,
    afecta_base_irpf: true,
    efecto_bruto:     'suma',
    efecto_neto:      'suma',
    formula_desc:     'Tabla Anexo I por cargo y nivel',
    formula_ejemplo:  'CMD N3: 3.624,66 €/mes · COP N3: 2.252,36 €/mes',
    motor_key:        'sb',
    estado:           CVN_ESTADO.IMPLEMENTADO,
    prioridad:        CVN_PRIORIDAD.CRITICA,
    confianza:        CVN_CONFIANZA.VALIDADO_NOMINA,
    impacto:          CVN_IMPACTO.NOMINA,
    fuente_nomina:    'Nóminas ESH feb-2026, mar-2026',
    notas_pendientes: '',
    relacionados:     ['plus_transporte', 'prorrata_extras'],
    faq_ids:          [],
  },

  {
    id:               'plus_transporte',
    nombre:           'Plus de Transporte',
    nombre_corto:     'Plus Transp.',
    categoria:        'fijos',
    tags:             ['mensual', 'fijo', 'anual'],
    articulo:         'Anexo I · BCSA 2026',
    boe:              null,
    vigencia_desde:   '2026-01-01',
    vigencia_hasta:   null,
    definicion:       'Complemento fijo mensual en concepto de desplazamiento al puesto de trabajo. Mismo importe para todos los cargos y niveles.',
    condiciones:      [
      'Importe anual 117,08 € — mensual 9,76 €',
      'No varía por nivel, base ni cargo',
    ],
    aplica_a:         ['CMD', 'COP', 'TCP', 'SCC', 'CC'],
    por_nivel:        false,
    por_base:         false,
    cotiza_ss:        true,
    tributa_irpf:     true,
    exento_hasta:     null,
    afecta_base_ss:   true,
    afecta_base_irpf: true,
    efecto_bruto:     'suma',
    efecto_neto:      'suma',
    formula_desc:     '117,08 € / 12',
    formula_ejemplo:  '9,76 €/mes',
    motor_key:        'plus_tr',
    estado:           CVN_ESTADO.IMPLEMENTADO,
    prioridad:        CVN_PRIORIDAD.ALTA,
    confianza:        CVN_CONFIANZA.VALIDADO_NOMINA,
    impacto:          CVN_IMPACTO.NOMINA,
    fuente_nomina:    'Nóminas ESH feb-2026',
    notas_pendientes: '',
    relacionados:     ['salario_base'],
    faq_ids:          [],
  },

  {
    id:               'prorrata_extras',
    nombre:           'Prorrata de Pagas Extra',
    nombre_corto:     'Extras',
    categoria:        'fijos',
    tags:             ['mensual', 'fijo', 'pagas', 'anual'],
    articulo:         'Anexo I · BCSA 2026',
    boe:              null,
    vigencia_desde:   '2026-01-01',
    vigencia_hasta:   null,
    definicion:       'Parte proporcional de las pagas extraordinarias prorrateada a lo largo de los 12 meses. Se percibe mensualmente y no en pagas separadas.',
    condiciones:      [
      'Depende del cargo y nivel igual que el salario base',
      'Incluida automáticamente en la nómina mensual',
    ],
    aplica_a:         ['CMD', 'COP', 'TCP', 'SCC', 'CC'],
    por_nivel:        true,
    por_base:         false,
    cotiza_ss:        true,
    tributa_irpf:     true,
    exento_hasta:     null,
    afecta_base_ss:   true,
    afecta_base_irpf: true,
    efecto_bruto:     'suma',
    efecto_neto:      'suma',
    formula_desc:     'Tabla Anexo I columna "extra" / 12',
    formula_ejemplo:  'CMD N3: 359,545 / 12 = 29,96 €/mes · COP N3: 187,70 / 12 = 15,64 €/mes',
    motor_key:        'extra',
    estado:           CVN_ESTADO.IMPLEMENTADO,
    prioridad:        CVN_PRIORIDAD.ALTA,
    confianza:        CVN_CONFIANZA.VALIDADO_NOMINA,
    impacto:          CVN_IMPACTO.NOMINA,
    fuente_nomina:    'Nóminas ESH feb-2026, mar-2026',
    notas_pendientes: '',
    relacionados:     ['salario_base'],
    faq_ids:          [],
  },

  // ─────────────────────────────────────────────────────────────
  // VARIABLES
  // ─────────────────────────────────────────────────────────────

  {
    id:               'horas_vuelo',
    nombre:           'Horas de Vuelo',
    nombre_corto:     'HV',
    categoria:        'variables',
    tags:             ['mensual', 'variable', 'tramos', 'nivel', 'vuelo'],
    articulo:         'Anexo I · BCSA 2026',
    boe:              null,
    vigencia_desde:   '2026-01-01',
    vigencia_hasta:   null,
    definicion:       'Retribución variable por horas de vuelo efectivas del mes. Se divide en 4 tramos con tarifas crecientes según cargo, nivel y base.',
    condiciones:      [
      'T1: primeras horas (tarifa ordinaria)',
      'T2: hasta 74 h acumuladas',
      'T3: hasta 89 h acumuladas',
      'T4: diferencial imaginarias/francos (horas de pago no voladas)',
      'Base MAD: factor ×1,20 sobre todos los tramos',
    ],
    aplica_a:         ['CMD', 'COP'],
    por_nivel:        true,
    por_base:         true,
    cotiza_ss:        true,
    tributa_irpf:     true,
    exento_hasta:     null,
    afecta_base_ss:   true,
    afecta_base_irpf: true,
    efecto_bruto:     'suma',
    efecto_neto:      'suma',
    formula_desc:     'Σ (nHV_Tx × tarifa_Tx) para T1 a T4',
    formula_ejemplo:  'CMD N3 base GC: T1 82,52 · T2 91,60 · T3 107,52 · T4 110,58 €/HV',
    motor_key:        'hvTotal',
    estado:           CVN_ESTADO.IMPLEMENTADO,
    prioridad:        CVN_PRIORIDAD.CRITICA,
    confianza:        CVN_CONFIANZA.VALIDADO_NOMINA,
    impacto:          CVN_IMPACTO.NOMINA,
    fuente_nomina:    'Nóminas ESH feb-2026 (13 per.), mar-2026 (9 per.)',
    notas_pendientes: '',
    relacionados:     ['imaginarias', 'francos', 'comp_mad', 'media_variables'],
    faq_ids:          ['faq_hv_vacaciones'],
  },

  {
    id:               'imaginarias',
    nombre:           'Imaginarias',
    nombre_corto:     'Im.',
    categoria:        'variables',
    tags:             ['mensual', 'variable', 'guardia', 'stand-by'],
    articulo:         'Anexo I · BCSA 2026',
    boe:              null,
    vigencia_desde:   '2026-01-01',
    vigencia_hasta:   null,
    definicion:       'Períodos de disponibilidad en guardia (stand-by). Cada imaginaria computa como 3 horas de vuelo T4 en la nómina.',
    condiciones:      [
      'Solo pilotos (CMD/COP)',
      'Factor: 1 imaginaria = 3 HV T4',
      'Si base MAD, el T4 también lleva ×1,20',
    ],
    aplica_a:         ['CMD', 'COP'],
    por_nivel:        true,
    por_base:         true,
    cotiza_ss:        true,
    tributa_irpf:     true,
    exento_hasta:     null,
    afecta_base_ss:   true,
    afecta_base_irpf: true,
    efecto_bruto:     'suma',
    efecto_neto:      'suma',
    formula_desc:     'nIm × 3 × tarifa_T4',
    formula_ejemplo:  '5 im. × 3 × 110,58 = 1.658,70 € (CMD N3 base GC)',
    motor_key:        'im',
    estado:           CVN_ESTADO.IMPLEMENTADO,
    prioridad:        CVN_PRIORIDAD.CRITICA,
    confianza:        CVN_CONFIANZA.VALIDADO_NOMINA,
    impacto:          CVN_IMPACTO.NOMINA,
    fuente_nomina:    'Nóminas ESH feb-2026',
    notas_pendientes: '',
    relacionados:     ['francos', 'horas_vuelo'],
    faq_ids:          ['faq_francos_im'],
  },

  {
    id:               'francos',
    nombre:           'Francos',
    nombre_corto:     'Fr.',
    categoria:        'variables',
    tags:             ['mensual', 'variable', 'descanso'],
    articulo:         'Anexo I · BCSA 2026',
    boe:              null,
    vigencia_desde:   '2026-01-01',
    vigencia_hasta:   null,
    definicion:       'Días de descanso operativo. Cada franco computa como 2 horas de vuelo T4 en la nómina.',
    condiciones:      [
      'Solo pilotos (CMD/COP)',
      'Factor: 1 franco = 2 HV T4',
      'Una imaginaria vale un 50% más que un franco',
    ],
    aplica_a:         ['CMD', 'COP'],
    por_nivel:        true,
    por_base:         true,
    cotiza_ss:        true,
    tributa_irpf:     true,
    exento_hasta:     null,
    afecta_base_ss:   true,
    afecta_base_irpf: true,
    efecto_bruto:     'suma',
    efecto_neto:      'suma',
    formula_desc:     'nFr × 2 × tarifa_T4',
    formula_ejemplo:  '3 fr. × 2 × 110,58 = 663,48 € (CMD N3 base GC)',
    motor_key:        'fr',
    estado:           CVN_ESTADO.IMPLEMENTADO,
    prioridad:        CVN_PRIORIDAD.ALTA,
    confianza:        CVN_CONFIANZA.VALIDADO_NOMINA,
    impacto:          CVN_IMPACTO.NOMINA,
    fuente_nomina:    'Nóminas ESH feb-2026',
    notas_pendientes: '',
    relacionados:     ['imaginarias', 'horas_vuelo'],
    faq_ids:          ['faq_francos_im'],
  },

  {
    id:               'dpo',
    nombre:           'DPO — Dirección por Objetivos',
    nombre_corto:     'DPO',
    categoria:        'variables',
    tags:             ['mensual', 'variable', 'objetivo'],
    articulo:         'BCSA 2026 — artículo exacto pendiente',
    boe:              null,
    vigencia_desde:   '2026-01-01',
    vigencia_hasta:   null,
    definicion:       'Complemento mensual variable ligado al cumplimiento de objetivos operativos. El importe varía cada mes y es notificado con las variables del período.',
    condiciones:      [
      'Importe variable según mes y objetivos',
      'No determinado por tablas fijas del convenio',
      'Se introduce manualmente desde las variables del mes',
    ],
    aplica_a:         ['CMD', 'COP', 'TCP', 'SCC', 'CC'],
    por_nivel:        false,
    por_base:         false,
    cotiza_ss:        true,
    tributa_irpf:     true,
    exento_hasta:     null,
    afecta_base_ss:   true,
    afecta_base_irpf: true,
    efecto_bruto:     'suma',
    efecto_neto:      'suma',
    formula_desc:     'Importe mensual según objetivos — entrada manual',
    formula_ejemplo:  '883,33 €/mes (ejemplo nómina real)',
    motor_key:        'dpo',
    estado:           CVN_ESTADO.IMPLEMENTADO,
    prioridad:        CVN_PRIORIDAD.ALTA,
    confianza:        CVN_CONFIANZA.VALIDADO_NOMINA,
    impacto:          CVN_IMPACTO.NOMINA,
    fuente_nomina:    'Nóminas ESH feb-2026',
    notas_pendientes: 'Localizar artículo exacto en el CC',
    relacionados:     ['media_variables'],
    faq_ids:          [],
  },

  // ─────────────────────────────────────────────────────────────
  // DIETAS
  // ─────────────────────────────────────────────────────────────

  {
    id:               'mant_nac',
    nombre:           'Manutención Nacional',
    nombre_corto:     'Mant. NAC',
    categoria:        'dietas',
    tags:             ['dieta', 'vuelo', 'Art.53', 'exenta', 'nacional'],
    articulo:         'Art. 53 · BCSA 2026',
    boe:              null,
    vigencia_desde:   '2026-01-01',
    vigencia_hasta:   null,
    definicion:       'Dieta por vuelo en destinos nacionales. Se percibe por período (ida o vuelta). Tiene tramo exento y tramo sujeto a IRPF. No cotiza a SS.',
    condiciones:      [
      'Total: 40,14 €/período',
      'Exento IRPF: 36,06 €/período',
      'Sujeto IRPF: 4,0756 €/período (verificado contra nóminas — no 4,08)',
      'No cotiza a SS',
    ],
    aplica_a:         ['CMD', 'COP', 'TCP', 'SCC', 'CC'],
    por_nivel:        false,
    por_base:         false,
    cotiza_ss:        false,
    tributa_irpf:     true,
    exento_hasta:     36.06,
    afecta_base_ss:   false,
    afecta_base_irpf: true,
    efecto_bruto:     'suma',
    efecto_neto:      'suma',
    formula_desc:     'nPer × 40,14 → exento nPer × 36,06 | sujeto nPer × 4,0756',
    formula_ejemplo:  '9 per.: 9 × 4,0756 = 36,68 € sujetos ✓ · 13 per.: 13 × 4,0756 = 52,98 ✓',
    motor_key:        'dMantNac',
    estado:           CVN_ESTADO.IMPLEMENTADO,
    prioridad:        CVN_PRIORIDAD.CRITICA,
    confianza:        CVN_CONFIANZA.VALIDADO_NOMINA,
    impacto:          CVN_IMPACTO.NOMINA,
    fuente_nomina:    'Nóminas ESH feb-2026 (13 per.) y mar-2026 (9 per.) — verificación cruzada',
    notas_pendientes: '',
    relacionados:     ['dieta_nac', 'dieta_int'],
    faq_ids:          ['faq_dietas_cotizan'],
  },

  {
    id:               'dieta_nac',
    nombre:           'Dieta Nacional (sin/con pernocta)',
    nombre_corto:     'Dieta NAC',
    categoria:        'dietas',
    tags:             ['dieta', 'nacional', 'exenta', 'pernocta'],
    articulo:         'BCSA 2026 — artículo exacto pendiente',
    boe:              null,
    vigencia_desde:   '2026-01-01',
    vigencia_hasta:   null,
    definicion:       'Compensación por desplazamiento en destino nacional. Dos variantes: sin pernocta (SP) y con pernocta (CP). Parte exenta y parte sujeta a IRPF.',
    condiciones:      [
      'NAC SP: 54,64 €/período — exento: 36,06 — sujeto: 18,58',
      'NAC CP: 54,64 €/período — exento: 53,34 — sujeto: 1,30',
      'No cotiza a SS',
    ],
    aplica_a:         ['CMD', 'COP', 'TCP', 'SCC', 'CC'],
    por_nivel:        false,
    por_base:         false,
    cotiza_ss:        false,
    tributa_irpf:     true,
    exento_hasta:     53.34,
    afecta_base_ss:   false,
    afecta_base_irpf: true,
    efecto_bruto:     'suma',
    efecto_neto:      'suma',
    formula_desc:     'nSP × 54,64 (exento 36,06) + nCP × 54,64 (exento 53,34)',
    formula_ejemplo:  '2 SP: sujeto 2 × 18,58 = 37,16 € · 1 CP: sujeto 1 × 1,30 = 1,30 €',
    motor_key:        'dNac',
    estado:           CVN_ESTADO.IMPLEMENTADO,
    prioridad:        CVN_PRIORIDAD.ALTA,
    confianza:        CVN_CONFIANZA.VALIDADO_NOMINA,
    impacto:          CVN_IMPACTO.NOMINA,
    fuente_nomina:    'Nóminas ESH feb-2026',
    notas_pendientes: 'Localizar artículo exacto en el CC',
    relacionados:     ['mant_nac', 'dieta_int'],
    faq_ids:          ['faq_dietas_cotizan'],
  },

  {
    id:               'dieta_int',
    nombre:           'Dieta Internacional (sin/con pernocta)',
    nombre_corto:     'Dieta INT',
    categoria:        'dietas',
    tags:             ['dieta', 'internacional', 'exenta', 'pernocta'],
    articulo:         'BCSA 2026 — artículo exacto pendiente',
    boe:              null,
    vigencia_desde:   '2026-01-01',
    vigencia_hasta:   null,
    definicion:       'Compensación por desplazamiento en destino internacional. Variante con pernocta (CP) exenta al 100%. Variante sin pernocta (SP) con tramo sujeto.',
    condiciones:      [
      'INT SP: 72,48 €/período — exento: 66,11 — sujeto: 6,36 (verificado: 1×6,36=6,36 ✓)',
      'INT CP: 72,48 €/período — exento: 72,48 (100% exento)',
      'Binter usa internamente 72,475 € (muestra 72,47; 2×72,475=144,95 ✓)',
      'No cotiza a SS',
    ],
    aplica_a:         ['CMD', 'COP', 'TCP', 'SCC', 'CC'],
    por_nivel:        false,
    por_base:         false,
    cotiza_ss:        false,
    tributa_irpf:     true,
    exento_hasta:     72.475,
    afecta_base_ss:   false,
    afecta_base_irpf: true,
    efecto_bruto:     'suma',
    efecto_neto:      'suma',
    formula_desc:     'nSP × 72,48 (exento 66,11) + nCP × 72,475 (exento 100%)',
    formula_ejemplo:  '1 INT SP: sujeto 6,36 € ✓ · 2 INT CP: 2 × 72,475 = 144,95 € exentos ✓',
    motor_key:        'dInt',
    estado:           CVN_ESTADO.IMPLEMENTADO,
    prioridad:        CVN_PRIORIDAD.ALTA,
    confianza:        CVN_CONFIANZA.VALIDADO_NOMINA,
    impacto:          CVN_IMPACTO.NOMINA,
    fuente_nomina:    'Nóminas ESH mar-2026',
    notas_pendientes: 'Localizar artículo exacto en el CC',
    relacionados:     ['mant_nac', 'dieta_nac'],
    faq_ids:          ['faq_dietas_cotizan'],
  },

  {
    id:               'compensatorio_dest',
    nombre:           'Compensatorio por Destacamento',
    nombre_corto:     'Comp. Dest.',
    categoria:        'dietas',
    tags:             ['dieta', 'destacamento', 'exenta'],
    articulo:         'BCSA 2026 — artículo exacto pendiente',
    boe:              null,
    vigencia_desde:   '2026-01-01',
    vigencia_hasta:   null,
    definicion:       'Compensación por desplazamiento en destacamento, tanto nacional como internacional. Exenta al 100% de IRPF. No cotiza a SS.',
    condiciones:      [
      'NAC: 44,65 €/período — exento total',
      'INT: 44,65 €/período — exento total',
      'No cotiza a SS',
    ],
    aplica_a:         ['CMD', 'COP', 'TCP', 'SCC', 'CC'],
    por_nivel:        false,
    por_base:         false,
    cotiza_ss:        false,
    tributa_irpf:     false,
    exento_hasta:     44.65,
    afecta_base_ss:   false,
    afecta_base_irpf: false,
    efecto_bruto:     'suma',
    efecto_neto:      'suma',
    formula_desc:     'nDestNac × 44,65 + nDestInt × 44,65 (ambos exentos)',
    formula_ejemplo:  '2 dest. nac.: 2 × 44,65 = 89,30 € (exentos)',
    motor_key:        'dDest',
    estado:           CVN_ESTADO.IMPLEMENTADO,
    prioridad:        CVN_PRIORIDAD.MEDIA,
    confianza:        CVN_CONFIANZA.VALIDADO_NOMINA,
    impacto:          CVN_IMPACTO.NOMINA,
    fuente_nomina:    'Nóminas ESH feb-2026',
    notas_pendientes: 'Localizar artículo exacto en el CC',
    relacionados:     ['dieta_nac', 'dieta_int'],
    faq_ids:          [],
  },

  // ─────────────────────────────────────────────────────────────
  // COMPLEMENTOS
  // ─────────────────────────────────────────────────────────────

  {
    id:               'comp_mad',
    nombre:           'Complemento Base Madrid',
    nombre_corto:     'Comp. MAD',
    categoria:        'complementos',
    tags:             ['base', 'MAD', 'factor', 'HV'],
    articulo:         'BCSA 2026 — artículo exacto pendiente',
    boe:              null,
    vigencia_desde:   '2026-01-01',
    vigencia_hasta:   null,
    definicion:       'Factor multiplicador ×1,20 aplicado a todos los tramos de HV para tripulaciones con base operativa en Madrid. PilotPay lo aplica automáticamente según el perfil.',
    condiciones:      [
      'Solo tripulaciones con base = MAD',
      'Factor ×1,20 sobre T1, T2, T3 y T4',
      'No afecta a salario base, pagas ni dietas',
    ],
    aplica_a:         ['CMD', 'COP'],
    por_nivel:        false,
    por_base:         true,
    cotiza_ss:        true,
    tributa_irpf:     true,
    exento_hasta:     null,
    afecta_base_ss:   true,
    afecta_base_irpf: true,
    efecto_bruto:     'suma',
    efecto_neto:      'suma',
    formula_desc:     'HV_Tx × 1,20 en lugar de HV_Tx × 1,00',
    formula_ejemplo:  'CMD N3: T1 82,52 × 1,20 = 99,02 ✓ · T2 91,60 × 1,20 = 109,92 ✓',
    motor_key:        'compMad',
    estado:           CVN_ESTADO.IMPLEMENTADO,
    prioridad:        CVN_PRIORIDAD.ALTA,
    confianza:        CVN_CONFIANZA.VALIDADO_NOMINA,
    impacto:          CVN_IMPACTO.NOMINA,
    fuente_nomina:    'Nómina ESH mar-2026',
    notas_pendientes: 'Localizar artículo exacto en el CC',
    relacionados:     ['horas_vuelo', 'jefatura_base'],
    faq_ids:          ['faq_comp_mad'],
  },

  {
    id:               'instruccion',
    nombre:           'Instrucción',
    nombre_corto:     'Instruc.',
    categoria:        'complementos',
    tags:             ['función', 'instructor', 'TRI', 'TRE'],
    articulo:         'BCSA 2026 — artículo pendiente de verificación',
    boe:              null,
    vigencia_desde:   null,
    vigencia_hasta:   null,
    definicion:       'Complemento percibido por pilotos habilitados como instructores de vuelo. Puede incluir instrucción en simulador (TRI/TRE) o en línea (OJT/IOE). El importe y las condiciones exactas están pendientes de verificación.',
    condiciones:      [
      'Requiere habilitación como instructor',
      'Puede variar según tipo (simulador vs. línea)',
      'No todos los comandantes son instructores',
    ],
    aplica_a:         ['CMD', 'COP'],
    por_nivel:        false,
    por_base:         false,
    cotiza_ss:        null,
    tributa_irpf:     null,
    exento_hasta:     null,
    afecta_base_ss:   null,
    afecta_base_irpf: null,
    efecto_bruto:     'pendiente',
    efecto_neto:      'pendiente',
    formula_desc:     'Pendiente — requiere nómina real de piloto instructor',
    formula_ejemplo:  '',
    motor_key:        null,
    estado:           CVN_ESTADO.PENDIENTE_EVIDENCIA,
    prioridad:        CVN_PRIORIDAD.ALTA,
    confianza:        CVN_CONFIANZA.EXPERIMENTAL,
    impacto:          CVN_IMPACTO.NOMINA,
    fuente_nomina:    null,
    notas_pendientes: 'Necesario: artículo CC + nómina real de instructor (TRI/TRE)',
    relacionados:     ['ltc', 'gti'],
    faq_ids:          ['faq_instruccion'],
  },

  // ─────────────────────────────────────────────────────────────
  // CARGOS ESPECIALES
  // ─────────────────────────────────────────────────────────────

  {
    id:               'ltc',
    nombre:           'LTC — Licencia de Tipo de Competencia',
    nombre_corto:     'LTC',
    categoria:        'cargos_especiales',
    tags:             ['habilitación', 'tipo', 'licencia', 'CMD', 'COP'],
    articulo:         'BCSA 2026 — artículo pendiente',
    boe:              null,
    vigencia_desde:   null,
    vigencia_hasta:   null,
    definicion:       'Habilitación que acredita que un piloto está certificado para operar un tipo específico de aeronave. Pendiente confirmar si genera complemento salarial directo o es solo una condición operativa.',
    condiciones:      [
      'Emitida por la AESA según normativa EASA',
      'Necesaria para ejercer como PIC o SIC del tipo',
      'Pendiente verificar impacto económico directo',
    ],
    aplica_a:         ['CMD', 'COP'],
    por_nivel:        false,
    por_base:         false,
    cotiza_ss:        null,
    tributa_irpf:     null,
    exento_hasta:     null,
    afecta_base_ss:   null,
    afecta_base_irpf: null,
    efecto_bruto:     'pendiente',
    efecto_neto:      'pendiente',
    formula_desc:     'Pendiente',
    formula_ejemplo:  '',
    motor_key:        null,
    estado:           CVN_ESTADO.PENDIENTE_EVIDENCIA,
    prioridad:        CVN_PRIORIDAD.MEDIA,
    confianza:        CVN_CONFIANZA.EXPERIMENTAL,
    impacto:          CVN_IMPACTO.NOMINA,
    fuente_nomina:    null,
    notas_pendientes: 'Confirmar si genera complemento o es solo condición. Necesario artículo CC + nómina real.',
    relacionados:     ['instruccion', 'gti'],
    faq_ids:          ['faq_ltc'],
  },

  {
    id:               'gti',
    nombre:           'GTI — Grupo de Trabajo de Instrucción',
    nombre_corto:     'GTI',
    categoria:        'cargos_especiales',
    tags:             ['instrucción', 'GTI', 'grupo'],
    articulo:         'BCSA 2026 — artículo pendiente',
    boe:              null,
    vigencia_desde:   null,
    vigencia_hasta:   null,
    definicion:       'Complemento o cargo asociado a la pertenencia al Grupo de Trabajo de Instrucción. Pendiente confirmar definición exacta, importe y condiciones.',
    condiciones:      [
      'Pendiente confirmar quiénes pertenecen al GTI',
      'Pendiente confirmar si genera complemento salarial',
    ],
    aplica_a:         ['CMD', 'COP'],
    por_nivel:        false,
    por_base:         false,
    cotiza_ss:        null,
    tributa_irpf:     null,
    exento_hasta:     null,
    afecta_base_ss:   null,
    afecta_base_irpf: null,
    efecto_bruto:     'pendiente',
    efecto_neto:      'pendiente',
    formula_desc:     'Pendiente',
    formula_ejemplo:  '',
    motor_key:        null,
    estado:           CVN_ESTADO.PENDIENTE_EVIDENCIA,
    prioridad:        CVN_PRIORIDAD.MEDIA,
    confianza:        CVN_CONFIANZA.EXPERIMENTAL,
    impacto:          CVN_IMPACTO.NOMINA,
    fuente_nomina:    null,
    notas_pendientes: 'Necesario: definición exacta del GTI, condiciones de pertenencia, artículo CC y nómina real.',
    relacionados:     ['instruccion', 'ltc'],
    faq_ids:          [],
  },

  {
    id:               'jefatura_base',
    nombre:           'Jefatura de Base',
    nombre_corto:     'Jef. Base',
    categoria:        'cargos_especiales',
    tags:             ['cargo', 'gestión', 'CMD', 'responsabilidad'],
    articulo:         'BCSA 2026 — artículo pendiente',
    boe:              null,
    vigencia_desde:   null,
    vigencia_hasta:   null,
    definicion:       'Complemento percibido por el piloto designado jefe de base. Implica responsabilidad sobre la operación y el personal de la base asignada.',
    condiciones:      [
      'Solo Comandantes',
      'Cargo de designación por la compañía',
      'Importe y condiciones pendientes de verificación',
    ],
    aplica_a:         ['CMD'],
    por_nivel:        false,
    por_base:         false,
    cotiza_ss:        null,
    tributa_irpf:     null,
    exento_hasta:     null,
    afecta_base_ss:   null,
    afecta_base_irpf: null,
    efecto_bruto:     'pendiente',
    efecto_neto:      'pendiente',
    formula_desc:     'Pendiente — importe y condiciones por confirmar',
    formula_ejemplo:  '',
    motor_key:        null,
    estado:           CVN_ESTADO.PENDIENTE_EVIDENCIA,
    prioridad:        CVN_PRIORIDAD.MEDIA,
    confianza:        CVN_CONFIANZA.EXPERIMENTAL,
    impacto:          CVN_IMPACTO.NOMINA,
    fuente_nomina:    null,
    notas_pendientes: 'Necesario: artículo CC, importe, nómina real de jefe de base.',
    relacionados:     ['comp_mad'],
    faq_ids:          [],
  },

  // ─────────────────────────────────────────────────────────────
  // IT / BAJAS
  // ─────────────────────────────────────────────────────────────

  {
    id:               'it_baja',
    nombre:           'Incapacidad Temporal (IT)',
    nombre_corto:     'IT / Baja',
    categoria:        'it_bajas',
    tags:             ['baja', 'IT', 'incidencia', 'SS', 'enfermedad'],
    articulo:         'LGSS + BCSA 2026 — mejoras CC por verificar',
    boe:              null,
    vigencia_desde:   '2026-01-01',
    vigencia_hasta:   null,
    definicion:       'Período de baja médica. La empresa complementa la prestación de la SS durante los primeros días. Su impacto real en la nómina generada es más complejo de lo que PilotPay calcula actualmente. El cálculo vigente es informativo.',
    condiciones:      [
      'Días 1-3: a cargo de la empresa (posible mejora CC)',
      'Días 4-15: SS abona 60% base reguladora + posible complemento empresa',
      'Desde día 16: pago delegado INSS',
      'Los conceptos variables (HV, imaginarias, francos) no se generan',
      'PilotPay: cálculo simplificado / informativo',
    ],
    aplica_a:         ['CMD', 'COP', 'TCP', 'SCC', 'CC'],
    por_nivel:        false,
    por_base:         false,
    cotiza_ss:        true,
    tributa_irpf:     true,
    exento_hasta:     null,
    afecta_base_ss:   true,
    afecta_base_irpf: true,
    efecto_bruto:     'resta',
    efecto_neto:      'resta',
    formula_desc:     'Depende de duración, período y mejoras CC — pendiente verificación',
    formula_ejemplo:  '',
    motor_key:        'baja',
    estado:           CVN_ESTADO.IMPLEMENTADO_PARCIAL,
    prioridad:        CVN_PRIORIDAD.CRITICA,
    confianza:        CVN_CONFIANZA.PARCIAL,
    impacto:          CVN_IMPACTO.NOMINA,
    fuente_nomina:    null,
    notas_pendientes: 'Para implementar correctamente: nómina real con IT + artículos CC de mejora + escenarios de pago delegado (día 16+).',
    relacionados:     ['licencias_retribuidas', 'maternidad_paternidad', 'media_variables'],
    faq_ids:          ['faq_it_perdida'],
  },

  // ─────────────────────────────────────────────────────────────
  // PERMISOS / LICENCIAS
  // ─────────────────────────────────────────────────────────────

  {
    id:               'licencias_retribuidas',
    nombre:           'Licencias Retribuidas',
    nombre_corto:     'Lic. Retrib.',
    categoria:        'permisos',
    tags:             ['permiso', 'licencia', 'derecho', 'retribuido'],
    articulo:         'BCSA 2026 — artículos específicos por tipo pendientes',
    boe:              null,
    vigencia_desde:   null,
    vigencia_hasta:   null,
    definicion:       'Permisos con retribución íntegra durante su disfrute: matrimonio, nacimiento, fallecimiento familiar, mudanza, enfermedad grave de familiar y otros supuestos del CC.',
    condiciones:      [
      'Se mantiene el 100% del salario durante el permiso',
      'Duración variable según tipo de licencia',
      'No impacto teórico en el cálculo mensual si se mantiene nómina',
    ],
    aplica_a:         ['CMD', 'COP', 'TCP', 'SCC', 'CC'],
    por_nivel:        false,
    por_base:         false,
    cotiza_ss:        null,
    tributa_irpf:     null,
    exento_hasta:     null,
    afecta_base_ss:   null,
    afecta_base_irpf: null,
    efecto_bruto:     'neutro',
    efecto_neto:      'neutro',
    formula_desc:     'Nómina íntegra — sin impacto teórico en el cálculo mensual estándar',
    formula_ejemplo:  '',
    motor_key:        null,
    estado:           CVN_ESTADO.PENDIENTE_EVIDENCIA,
    prioridad:        CVN_PRIORIDAD.ALTA,
    confianza:        CVN_CONFIANZA.EXPERIMENTAL,
    impacto:          CVN_IMPACTO.ADMINISTRATIVO,
    fuente_nomina:    null,
    notas_pendientes: 'Necesario: catálogo completo de tipos, duración de cada una y condiciones del CC.',
    relacionados:     ['maternidad_paternidad', 'it_baja'],
    faq_ids:          ['faq_licencias'],
  },

  {
    id:               'maternidad_paternidad',
    nombre:           'Maternidad / Paternidad',
    nombre_corto:     'Mat. / Pat.',
    categoria:        'permisos',
    tags:             ['permiso', 'INSS', 'nacimiento', 'baja'],
    articulo:         'LGSS + BCSA 2026 — mejoras CC pendientes',
    boe:              null,
    vigencia_desde:   null,
    vigencia_hasta:   null,
    definicion:       'Suspensión del contrato por nacimiento o adopción. Prestación a cargo del INSS (100% base reguladora). El CC puede establecer complementos si la base reguladora no cubre el salario real.',
    condiciones:      [
      'Maternidad: 16 semanas · Paternidad: 16 semanas (desde 2021)',
      'Prestación base: 100% base reguladora (INSS)',
      'Posible complemento empresa si base reguladora < salario real',
      'Gestión como pago delegado o directo según caso',
    ],
    aplica_a:         ['CMD', 'COP', 'TCP', 'SCC', 'CC'],
    por_nivel:        false,
    por_base:         false,
    cotiza_ss:        null,
    tributa_irpf:     null,
    exento_hasta:     null,
    afecta_base_ss:   null,
    afecta_base_irpf: null,
    efecto_bruto:     'pendiente',
    efecto_neto:      'pendiente',
    formula_desc:     'Pendiente — depende de base reguladora y mejoras CC',
    formula_ejemplo:  '',
    motor_key:        null,
    estado:           CVN_ESTADO.PENDIENTE_EVIDENCIA,
    prioridad:        CVN_PRIORIDAD.ALTA,
    confianza:        CVN_CONFIANZA.EXPERIMENTAL,
    impacto:          CVN_IMPACTO.ADMINISTRATIVO,
    fuente_nomina:    null,
    notas_pendientes: 'Necesario: artículos CC de mejora + nómina real + estructura de pago delegado.',
    relacionados:     ['it_baja', 'licencias_retribuidas'],
    faq_ids:          ['faq_maternidad'],
  },

  // ─────────────────────────────────────────────────────────────
  // VARIABLES ACUMULADAS
  // ─────────────────────────────────────────────────────────────

  {
    id:               'media_variables',
    nombre:           'Media de Variables',
    nombre_corto:     'Media Var.',
    categoria:        'acumuladas',
    tags:             ['acumulada', 'vacaciones', 'variable', 'media'],
    articulo:         'BCSA 2026 — artículo exacto pendiente',
    boe:              null,
    vigencia_desde:   '2026-01-01',
    vigencia_hasta:   null,
    definicion:       'Importe percibido durante vacaciones como compensación por los conceptos variables (HV, imaginarias, etc.) que no se generan ese mes al no volar. Equivale a la media de esos conceptos en los últimos 12 meses. Tributa IRPF. En PilotPay se introduce manualmente; el cálculo automático desde el histórico está pendiente.',
    condiciones:      [
      'Se percibe en el mes de vacaciones',
      'Sustituye a los conceptos variables que no se generan',
      'Tributa IRPF — suma al devengado',
      'No cotiza a SS (pendiente confirmar)',
      'PilotPay: entrada manual — cálculo automático en desarrollo',
    ],
    aplica_a:         ['CMD', 'COP', 'TCP', 'SCC', 'CC'],
    por_nivel:        false,
    por_base:         false,
    cotiza_ss:        false,
    tributa_irpf:     true,
    exento_hasta:     null,
    afecta_base_ss:   false,
    afecta_base_irpf: true,
    efecto_bruto:     'suma',
    efecto_neto:      'suma',
    formula_desc:     'Media(variables_últimos_12_meses) — cálculo automático pendiente',
    formula_ejemplo:  'Si media HV = 1.800 €/mes → se perciben ≈1.800 € en vacaciones',
    motor_key:        'mediaVariables',
    estado:           CVN_ESTADO.IMPLEMENTADO_PARCIAL,
    prioridad:        CVN_PRIORIDAD.ALTA,
    confianza:        CVN_CONFIANZA.VALIDADO_CONVENIO,
    impacto:          CVN_IMPACTO.NOMINA,
    fuente_nomina:    null,
    notas_pendientes: 'Cálculo automático desde histórico mensual pendiente. Requiere MonthRecords de los últimos 12 meses. Confirmar artículo exacto CC y si cotiza o no a SS.',
    relacionados:     ['horas_vuelo', 'it_baja'],
    faq_ids:          ['faq_media_variables'],
  },

  // ─────────────────────────────────────────────────────────────
  // UNIFORMIDAD
  // ─────────────────────────────────────────────────────────────

  {
    id:               'uniformidad',
    nombre:           'Uniformidad',
    nombre_corto:     'Uniform.',
    categoria:        'uniformidad',
    tags:             ['operativo', 'puntos', 'prendas', 'dotación'],
    articulo:         'BCSA 2026 — artículo pendiente',
    boe:              null,
    vigencia_desde:   null,
    vigencia_hasta:   null,
    definicion:       'Sistema de dotación de uniformidad para la tripulación mediante puntos anuales canjeables por prendas del catálogo de Binter. No tiene impacto económico directo en la nómina.',
    condiciones:      [
      'Puntos asignados anualmente según cargo',
      'Canje por prendas del catálogo oficial',
      'Puntos no usados no se compensan en dinero',
      'Sin impacto en nómina',
    ],
    aplica_a:         ['CMD', 'COP', 'TCP', 'SCC', 'CC'],
    por_nivel:        false,
    por_base:         false,
    cotiza_ss:        false,
    tributa_irpf:     false,
    exento_hasta:     null,
    afecta_base_ss:   false,
    afecta_base_irpf: false,
    efecto_bruto:     'neutro',
    efecto_neto:      'neutro',
    formula_desc:     'Sistema de puntos — sin impacto en nómina',
    formula_ejemplo:  'X puntos/año según cargo — tabla pendiente',
    motor_key:        null,
    estado:           CVN_ESTADO.PENDIENTE_EVIDENCIA,
    prioridad:        CVN_PRIORIDAD.MEDIA,
    confianza:        CVN_CONFIANZA.EXPERIMENTAL,
    impacto:          CVN_IMPACTO.OPERATIVO,
    fuente_nomina:    null,
    notas_pendientes: 'Necesario: tabla de puntos por cargo, catálogo de prendas y valores.',
    relacionados:     [],
    faq_ids:          ['faq_uniformidad'],
  },

];  // fin CONVENIO_CONCEPTOS


// ── Consultas frecuentes ──────────────────────────────────────────

const CONVENIO_FAQS = [

  {
    id:           'faq_it_perdida',
    pregunta:     '¿Cuánto pierdo económicamente en una IT?',
    respuesta:    'Durante los primeros 3 días la empresa asume el coste (puede haber mejora CC). Del día 4 al 15, la SS abona el 60% de la base reguladora y el CC puede establecer complemento hasta el 100%. Desde el día 16, el INSS paga directamente (pago delegado). Los conceptos variables —HV, imaginarias, francos— no se generan ese mes. PilotPay calcula actualmente el efecto de forma simplificada.',
    concepto_ids: ['it_baja'],
    categoria:    'it_bajas',
    dificultad:   'tecnica',
    verificada:   false,
    confianza:    CVN_CONFIANZA.PARCIAL,
    fuente:       'LGSS + CC — pendiente verificar mejoras específicas BCSA',
  },

  {
    id:           'faq_media_variables',
    pregunta:     '¿Qué es la media de variables y cuándo se cobra?',
    respuesta:    'Es el importe que recibes en el mes de vacaciones para compensar los conceptos variables (HV, imaginarias, etc.) que no generas al no volar. Se calcula como la media de esos conceptos en los últimos 12 meses. Tributa IRPF. Según el convenio no cotiza a la SS, aunque está pendiente confirmar el artículo exacto. En PilotPay se introduce manualmente; el cálculo automático desde el histórico está en desarrollo.',
    concepto_ids: ['media_variables', 'horas_vuelo'],
    categoria:    'acumuladas',
    dificultad:   'basica',
    verificada:   false,
    confianza:    CVN_CONFIANZA.VALIDADO_CONVENIO,
    fuente:       'Convenio BCSA 2026 — artículo exacto pendiente',
  },

  {
    id:           'faq_dietas_cotizan',
    pregunta:     '¿Qué dietas cotizan a la Seguridad Social?',
    respuesta:    'Las dietas en Binter tienen un tramo exento y un tramo sujeto según los límites de la AEAT. La parte sujeta cotiza a SS y tributa a IRPF. Ejemplos verificados: manutención nacional (Art. 53) —36,06 € exentos, 4,0756 € sujetos por período—. La dieta internacional con pernocta está exenta al 100%. Las nacionales con pernocta tienen un tramo sujeto menor que sin pernocta. El compensatorio por destacamento es exento total.',
    concepto_ids: ['mant_nac', 'dieta_nac', 'dieta_int', 'compensatorio_dest'],
    categoria:    'dietas',
    dificultad:   'tecnica',
    verificada:   true,
    confianza:    CVN_CONFIANZA.VALIDADO_NOMINA,
    fuente:       'Nóminas ESH feb-2026 y mar-2026 — verificación cruzada',
  },

  {
    id:           'faq_francos_im',
    pregunta:     '¿Los francos y las imaginarias computan igual en la nómina?',
    respuesta:    'No. Ambos se convierten en horas T4, pero con factores distintos. 1 imaginaria = 3 HV T4. 1 franco = 2 HV T4. Una imaginaria vale un 50% más que un franco en la nómina. Ambos cotizan y tributan igual que el resto de HV. Si tienes base MAD, ambos llevan también el factor ×1,20.',
    concepto_ids: ['francos', 'imaginarias', 'horas_vuelo'],
    categoria:    'variables',
    dificultad:   'basica',
    verificada:   true,
    confianza:    CVN_CONFIANZA.VALIDADO_NOMINA,
    fuente:       'Nóminas ESH feb-2026 — verificado',
  },

  {
    id:           'faq_comp_mad',
    pregunta:     '¿Qué es el complemento base MAD y cómo afecta a la nómina?',
    respuesta:    'Factor ×1,20 sobre todas tus horas de vuelo (T1 a T4) si tienes base operativa en Madrid. Significa que cobras un 20% más por hora volada que un compañero en Canarias. El salario base, pagas y dietas no se ven afectados. PilotPay lo aplica automáticamente si tu perfil tiene base = MAD.',
    concepto_ids: ['comp_mad', 'horas_vuelo'],
    categoria:    'complementos',
    dificultad:   'basica',
    verificada:   true,
    confianza:    CVN_CONFIANZA.VALIDADO_NOMINA,
    fuente:       'Nómina ESH mar-2026 — T1×1,20=99,02 ✓ T2×1,20=109,92 ✓',
  },

  {
    id:           'faq_hv_vacaciones',
    pregunta:     '¿Cómo afectan las vacaciones a mis horas de vuelo?',
    respuesta:    'En el mes de vacaciones no vuelas, por lo que no generas HV, imaginarias ni francos. Para compensarlo percibes la "Media de Variables": el promedio de esos conceptos en los últimos 12 meses. Tu nómina en vacaciones no cae a cero en la parte variable, aunque puede ser distinta al mes habitual.',
    concepto_ids: ['horas_vuelo', 'media_variables'],
    categoria:    'variables',
    dificultad:   'basica',
    verificada:   false,
    confianza:    CVN_CONFIANZA.VALIDADO_CONVENIO,
    fuente:       'Convenio BCSA 2026 — artículo exacto pendiente',
  },

  {
    id:           'faq_instruccion',
    pregunta:     '¿Cómo computa la instrucción en la nómina?',
    respuesta:    'La instrucción genera un complemento para pilotos con habilitación de instructor (TRI/TRE). El importe exacto, si varía según tipo de instrucción y las condiciones del CC están pendientes de verificación. PilotPay no calcula este concepto todavía. Si eres instructor, el importe real aparece en tu nómina empresa.',
    concepto_ids: ['instruccion', 'ltc'],
    categoria:    'complementos',
    dificultad:   'tecnica',
    verificada:   false,
    confianza:    CVN_CONFIANZA.EXPERIMENTAL,
    fuente:       'Pendiente — requiere nómina real de instructor + artículo CC',
  },

  {
    id:           'faq_ltc',
    pregunta:     '¿Qué es la LTC y genera complemento en la nómina?',
    respuesta:    'LTC es la Licencia de Tipo de Competencia: la habilitación que acredita que un piloto está certificado para operar un tipo específico de aeronave. Si genera un complemento salarial directo o solo es una condición operativa está pendiente de verificación contra el convenio y nóminas reales.',
    concepto_ids: ['ltc', 'instruccion'],
    categoria:    'cargos_especiales',
    dificultad:   'tecnica',
    verificada:   false,
    confianza:    CVN_CONFIANZA.EXPERIMENTAL,
    fuente:       'Pendiente — requiere verificación CC y nómina real',
  },

  {
    id:           'faq_maternidad',
    pregunta:     '¿Qué mantiene la empresa durante baja por maternidad o paternidad?',
    respuesta:    'La prestación la abona el INSS y suele ser el 100% de la base reguladora. El CC puede establecer un complemento si esa base reguladora no cubre el salario real. El impacto exacto en la nómina depende de la base reguladora individual, el tipo de gestión (pago delegado o directo) y las mejoras del CC. Está pendiente de verificación con nóminas reales.',
    concepto_ids: ['maternidad_paternidad', 'it_baja'],
    categoria:    'permisos',
    dificultad:   'tecnica',
    verificada:   false,
    confianza:    CVN_CONFIANZA.EXPERIMENTAL,
    fuente:       'LGSS + CC — pendiente verificar artículos y nóminas reales',
  },

  {
    id:           'faq_licencias',
    pregunta:     '¿Qué pasa con la nómina en una licencia no retribuida?',
    respuesta:    'En una licencia no retribuida la empresa no abona retribución durante el período. La cotización a la SS y el cómputo de antigüedad pueden variar según el tipo y duración. Los detalles exactos por tipo de licencia y las condiciones específicas del CC están pendientes de documentación.',
    concepto_ids: ['licencias_retribuidas'],
    categoria:    'permisos',
    dificultad:   'tecnica',
    verificada:   false,
    confianza:    CVN_CONFIANZA.EXPERIMENTAL,
    fuente:       'Pendiente — requiere artículos CC y tipos de licencia',
  },

  {
    id:           'faq_uniformidad',
    pregunta:     '¿Cuántos puntos de uniformidad tengo y qué prendas me corresponden?',
    respuesta:    'El CC establece un sistema de puntos anuales según cargo que se canjean por prendas del catálogo de uniformidad de Binter. Los puntos no usados no se compensan en dinero. La tabla de puntos por cargo y el catálogo completo de prendas está pendiente de documentación en PilotPay. Este concepto no tiene impacto en la nómina.',
    concepto_ids: ['uniformidad'],
    categoria:    'uniformidad',
    dificultad:   'basica',
    verificada:   false,
    confianza:    CVN_CONFIANZA.EXPERIMENTAL,
    fuente:       'Convenio BCSA 2026 — artículo pendiente',
  },

];  // fin CONVENIO_FAQS


// ── Helpers de consulta ───────────────────────────────────────────

const ConvenioEngine = {

  getConcepto(id) {
    return CONVENIO_CONCEPTOS.find(c => c.id === id) || null;
  },

  getByCategoria(cat) {
    return CONVENIO_CONCEPTOS.filter(c => c.categoria === cat);
  },

  getByEstado(estado) {
    return CONVENIO_CONCEPTOS.filter(c => c.estado === estado);
  },

  getByMotorKey(key) {
    return CONVENIO_CONCEPTOS.find(c => c.motor_key === key) || null;
  },

  search(query) {
    if (!query) return CONVENIO_CONCEPTOS;
    const q = query.toLowerCase();
    return CONVENIO_CONCEPTOS.filter(c =>
      c.nombre.toLowerCase().includes(q) ||
      c.definicion.toLowerCase().includes(q) ||
      c.tags.some(t => t.toLowerCase().includes(q)) ||
      (c.articulo || '').toLowerCase().includes(q)
    );
  },

  getFAQ(id) {
    return CONVENIO_FAQS.find(f => f.id === id) || null;
  },

  getFAQsByConcepto(conceptoId) {
    return CONVENIO_FAQS.filter(f => f.concepto_ids.includes(conceptoId));
  },

  statsImplementados() {
    const total = CONVENIO_CONCEPTOS.length;
    const impl  = CONVENIO_CONCEPTOS.filter(c => c.estado === CVN_ESTADO.IMPLEMENTADO).length;
    const parc  = CONVENIO_CONCEPTOS.filter(c => c.estado === CVN_ESTADO.IMPLEMENTADO_PARCIAL).length;
    const pend  = total - impl - parc;
    return { total, impl, parc, pend };
  },

};
